from active_projects.ode.part1.pendulum import *
from active_projects.ode.part1.staging import *
from active_projects.ode.part1.pi_scenes import *
from active_projects.ode.part1.phase_space import *
from active_projects.ode.part1.wordy_scenes import *

OUTPUT_DIRECTORY = "ode/part1"
SCENES_IN_ORDER = [
    WhenChangeIsEasier,
    VectorFieldTest,
    IntroducePendulum,
    MultiplePendulumsOverlayed,
    PeriodFormula,
    FormulasAreLies,
    MediumAnglePendulum,
    MediumHighAnglePendulum,
    HighAnglePendulum,
    LowAnglePendulum,
    SomeOfYouWatching,
    SmallAngleApproximationTex,
    VeryLowAnglePendulum,
    FormulasAreLies,
    TourOfDifferentialEquations,
    WherePendulumLeads,
    LongDoublePendulum,
    # FollowThisThread,
    StrogatzQuote,
    ShowHorizontalDashedLine,
    RabbitFoxPopulations,
    RabbitFoxEquation,
    # Something...
    ShowSimpleTrajectory,
    SimpleProjectileEquation,
    SimpleProjectileEquationVGraphFreedom,
    ShowGravityAcceleration,
    UniversalGravityLawSymbols,
    ExampleTypicalODE,
    AnalyzePendulumForce,
    ShowSineValues,
    BuildUpEquation,
    AirResistanceBrace,
    ShowDerivativeVideo,
    SubtleAirCurrents,
    SimpleDampenedPendulum,
    DefineODE,
    SecondOrderEquationExample,
    ODEvsPDEinFrames,
    ProveTeacherWrong,
    SetAsideSeekingSolution,
    #
    WriteInRadians,
    XEqLThetaToCorner,
    ComingUp,
    InputLabel,
    SoWhatIsThetaThen,
    ReallyHardToSolve,
    ReasonForSolution,
    PhysicistPhaseSpace,
    GleickQuote,
    SpectrumOfStartingStates,
    WritePhaseFlow,
    AskAboutStability,
    LoveExample,
    PassageOfTime,
    LovePhaseSpace,
    ComparePhysicsToLove,
    FramesComparingPhysicsToLove,
    SetupToTakingManyTinySteps,
    ShowClutterPrevention,
    # VisualizeHeightSlopeCurvature,
    VisualizeStates,
    ReferencePiCollisionStateSpaces,
    IntroduceVectorField,
    XComponentArrows,
    BreakingSecondOrderIntoTwoFirstOrder,
    ShowPendulumPhaseFlow,
    ShowHighVelocityCase,
    TweakMuInFormula,
    TweakMuInVectorField,
    FromODEToVectorField,
    LorenzVectorField,
    ThreeBodiesInSpace,
    AltThreeBodiesInSpace,
    TwoBodiesInSpace,
    TwoBodiesWithZPart,
    ThreeBodyTitle,
    ThreeBodySymbols,
    #
    HighAmplitudePendulum,
    WritePhaseSpace,
    #
    AskAboutActuallySolving,
    WriteODESolvingCode,
    TakeManyTinySteps,
    ManyStepsFromDifferentStartingPoints,
    InaccurateComputation,
    HungerForExactness,
    ShowRect,
    ShowSquare,
    JumpToThisPoint,
    ThreeBodyEquation,
    ItGetsWorse,
    ChaosTitle,
    RevisitQuote,
    EndScreen,
    Thumbnail,
]
